name: "Liquid-JS/release-tag"
description: "Create a release on tag push"
inputs:
  tag_name:
    description: "The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag"
    required: true
  release_name:
    description: "The name of the release. For example, `Release v1.0.1`"
    required: false
  draft:
    description: "`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`"
    required: false
    default: false
  no_contributors:
    description: "`true` to skip contributors section when generating changelog. Default: `false`"
    required: false
    default: false
runs:
  using: "node20"
  main: "lib/index.js"
branding:
  icon: "tag"
  color: "gray-dark"
